info:
  contact: {}
paths:
  /apps:
    get:
      consumes:
      - application/json
      description: Get paginated information of all applications
      parameters:
      - description: Number of pages
        in: query
        name: page
        type: string
      - description: Elements per page
        in: query
        name: perpage
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
        default:
          description: error
          schema:
            type: string
      summary: Get all applications for a given team
swagger: "2.0"
