run:
  issues-exit-code: 1 #Default
  tests: true #Default

linters:
  enable:
    - gofmt
    - whitespace
    - goimports
    - golint

linters-settings:
  errcheck:
    ignore: github.com/mgutz/logxi/v1:Error|Warn|Debug

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/kinvolk/nebraska
