language: go
sudo: required

go:
  - "1.11.x"

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker pull coreroller/postgres
  - sudo service docker restart ; sleep 10
  - docker run --privileged -d -p 127.0.0.1:5432:5432 coreroller/postgres
  - docker ps -a

# at most one test at a time is ran, because most of the tests write
# to the single database instance
script:
  - LOGXI=* go test -p 1 -v ./...
