# Docker-compose file for interactive and for automated testing.
#
# Build docker image from local sources:
#   docker-compose --file docker-compose.test.yaml build
#
# Run:
#   docker-compose --file docker-compose.test.yaml run
# Run with persistent storage:
#   docker-compose --file docker-compose.test.yaml --file docker-compose.test-db-persist.yaml up
#
# See docker-compose.pg-persist.yaml for more informatino on persistent storage.

version: "3.9"

services:
  postgres:
    image: postgres:12.9
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: nebraska
      POSTGRES_DB: nebraska_tests
      POSTGRES_USER: postgres
      TZ: UTC 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

  server:
    build: 
      context: ../
      dockerfile: Dockerfile
      network: host
    ports:
      - "8002:8000"
    # The "long form" depends_on silently fails in some scenarios (we've seen this with podman)
    #  so the short form is added for compatibility.
    depends_on:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NEBRASKA_DB_URL=postgres://postgres:nebraska@postgres:5432/nebraska_tests?sslmode=disable&connect_timeout=10
    command: sh -c "/nebraska/nebraska --auth-mode=noop --http-static-dir=/nebraska/static --api-endpoint-suffix=/"
