{{- if .Values.config.hostFlatcarPackages.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nebraska.fullname" . }}-packages
  labels:
    {{- include "nebraska.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.config.hostFlatcarPackages.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.config.hostFlatcarPackages.persistence.size }}
  {{- if .Values.config.hostFlatcarPackages.persistence.storageClass }}
  storageClassName: {{ .Values.config.hostFlatcarPackages.persistence.storageClass }}
  {{- end }}
{{- end }}
