{{- if and .Values.ingress.enabled .Values.ingress.update.enabled }}
{{- $fullName := include "nebraska.fullname" . }}
{{- $svcPort := .Values.service.port }}
{{- $kubeGitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- if semverCompare ">=1.19-0" $kubeGitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeGitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName | trunc 56 | trimSuffix "-" }}-update
  labels:
    {{- include "nebraska.labels" . | nindent 4 }}
  {{- with .Values.ingress.update.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /v1/update
            backend:
            {{- if semverCompare ">=1.19-0" $kubeGitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            pathType: ImplementationSpecific
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
          - path: /flatcar
            backend:
            {{- if semverCompare ">=1.19-0" $kubeGitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            pathType: ImplementationSpecific
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
    {{- end }}
  {{- end }}
