name: Build Backend
on:
  pull_request:
    paths:
    - 'cmd/**'
    - 'pkg/**'
    - 'go.mod'
    - 'go.sum'
    - 'updaters/**'

jobs:

  build:
    name: Lint & Build
    runs-on: ubuntu-18.04

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Lint
      run: |
        # @todo: Extract this into scripts that can also be used out of the CI
        export GOPATH=${RUNNER_WORKSPACE}/go
        export GO111MODULES=on
        cd $GITHUB_WORKSPACE
        go build -o ./tools/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
        ./tools/golangci-lint run ./cmd/... ./pkg/...

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        make backend
