name: Build Frontend

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: run ci
      run: |
        make ci
      working-directory: frontend
