name: Build Frontend

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: run ci
      run: |
        make ci
      working-directory: frontend
