name: Build Frontend

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22]

    steps:
    - name: Check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: ${{ matrix.node-version }}

    - name: run ci
      run: |
        make ci
      working-directory: frontend
