name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 5
    - name: Deploy Playwright Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ !cancelled() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
        publish_branch: gh-pages
