name: updater
on:
  pull_request:
    paths:
    - 'updater/**'

permissions:
  contents: read

jobs:
  build:
    name: Test updater library
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up Go 1.22
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: 1.22.x
      id: go

    - name: Start postgres dependency
      run: |
        docker compose -f backend/docker-compose.test.yaml up -d postgres

    - name: Test library
      env:
        NEBRASKA_DB_URL: "postgres://postgres:nebraska@127.0.0.1:8001/nebraska_tests?sslmode=disable&connect_timeout=10"
      run: |
        cd updater
        go test -v ./...
